### ISSUE TITLE
gfx.py - fill_triangle broken for flat topped triangles

### ISSUE THREAD

**Issue by jeffmer** [adafruit/Adafruit_CircuitPython_GFX#2]
Lines from 199 in fill_triangle should be:
        sa = 0
        sb = 0
        if y1 == y2:
            last = y1
        else:
            last = y1-1
        y = y0
        while y <= last:
which is a better translation of the original Adafruit c -code 
needs y+=1 at end of loop

**Comment by kattni** [comment]
This appears to have been resolved.

**Comment by nitko12** [comment]
I'm facing the same issue on my [repo](https://github.com/nitko12/micropython-inkplate6), 
when y coordinates of 2 points are the same, it fills the triangle all the way up,

First picture is when I call
display.fillTriangle(400, 150, 300, 100, 400, 100, display.BLACK)
and the second is when 
display.fillTriangle(400, 150, 300, 101, 400, 100, display.BLACK)
is called.

![1](https://user-images.githubusercontent.com/34972330/93338554-c2e00e80-f82a-11ea-8be8-0f0ce5cec294.jpg)
![2](https://user-images.githubusercontent.com/34972330/93338563-c70c2c00-f82a-11ea-88ad-75665fefb8ba.jpg)
