### ISSUE TITLE
Library missing from Adafruit CircuitPython Bundle

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_GFX#27]
This bundle needs to be added to the [Adafruit CircuitPyhon Bundle](https://github.com/adafruit/Adafruit_CircuitPython_Bundle).  Instructions for doing so can be found [here in this Learn Guide](https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/sharing-in-the-community-bundle).

**Comment by jposada202020** [comment]
solved by https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/422
