### ISSUE TITLE
Possible bug in fill_triangle() method

### ISSUE THREAD

**Issue by peter-l5** [adafruit/Adafruit_CircuitPython_GFX#33]
The fill_triangle method seems to be drawing triangles incorrectly around the middle vertex (in the vertical direction). This appears to be related to the method drawing a horizontal line with the same y co-ordinate twice at the level of the middle vertex. The behaviour happens because the final value of the loop variable y in the loop used to fill the top part of the triangle is repeated for the first line used to fill the bottom part of the triangle. The code from the two loops is below for reference. 

The images below illustrate the issue around the middle vertex.

I have developed and tested a fix for this employed in the repository [framebuf2](https://github.com/peter-l5/framebuf2) and will post it here as a pull request separately in the next day or two. While I realise that this library is due to be deprecated soon, I figure it may still be worthwhile to fix it.
```
        for y in range(y0, last + 1):
            a = x0 + sa // dy01
            b = x0 + sb // dy02
            sa += dx01
            sb += dx02
            if a > b:
                a, b = b, a
            self.hline(a, y, b - a + 1, *args, **kwargs)
        sa = dx12 * (y - y1)
        sb = dx02 * (y - y0)
        while y <= y2:
            a = x1 + sa // dy12
            b = x0 + sb // dy02
            sa += dx12
            sb += dx02
            if a > b:
                a, b = b, a
            self.hline(a, y, b - a + 1, *args, **kwargs)
            y += 1
```
![fill_triangle_issue1](https://user-images.githubusercontent.com/105649844/236427063-ea211953-b75a-4db7-9071-52718c251b70.jpg)
![fill_triangle_issue2](https://user-images.githubusercontent.com/105649844/236427067-82b2ef57-4b67-42ae-843a-1ebb549ccc18.jpg)

**Comment by peter-l5** [comment]
Hi, I submitted some code to fix this under #34, however this failed the automated workflow testing before getting to a stage where it could be reviewed. I'm afraid I don't know how to resolve this issue.

**Comment by jposada202020** [comment]
Hello @peter-l5 :), you could use pre-commit, it would reformat the files for the CI to pass. You could follow the instructions here
https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code
or here
https://learn.adafruit.com/improve-your-code-with-pylint/overview

If you have any further questions, we could discuss in the Adafruit discord server :).

**Comment by peter-l5** [comment]
Thanks! I will take a look and try that out, might be a few days before I can pick this up again - just to be aware.

**Comment by jposada202020** [comment]
No worries :) take your time
