### ISSUE TITLE
gfx_simpletest.py is empty?

### ISSUE THREAD

**Issue by AdinAck** [adafruit/Adafruit_CircuitPython_GFX#7]
gfx_simpletest.py is empty and I can not find any documentation as to how to use this library!

**Comment by dherrada** [comment]
@kattni Have the ili3940 micropython examples you merged been tested with Circuitpython. If so, I can rename ili3940_test.py to gfx_simpletest.py

**Comment by AdinAck** [comment]
Parts of it work for the display I am using. I figured out how to use it also. Thanks!

**Comment by dherrada** [comment]
@AdinAck does the entire ili3940_test.py file work or did you have to modify it? If you did, I'd love it if you could send me the modified file and we could see about making it the new gfx_simpletest.py

**Comment by AdinAck** [comment]
I had to modify it because my display is not the ili3940. I am using the SSD1322 which does not have a "display.pixel" function so I had to make one for it. The "hline=fast_hline" and "vline=fast_vline" doesn't work because there are no "fast_hline" or "fast_vline" functions in "adafruit_gfx.py". Everything else was the same for me, but that is only for my display. If you want I could still send a version that works for the SSD1322?

**Comment by dherrada** [comment]
That'd be great. I'm going to combine the two files into the simpletest file and have you test it your ssd1322 and then try to find the ili3940 that I think I've got lying around somewhere and test it on that

**Comment by AdinAck** [comment]
Here you go! (It wouldn't let me upload a .py so I just copied and pasted it)

import board
import busio
import time
import displayio
import adafruit_ssd1322
import adafruit_gfx as gfx

displayio.release_displays()

# Initialize screen
d_spi = busio.SPI(board.SCL, board.SDA)
d_cd = board.D6
d_dc = board.D9
d_rst = board.D5

d_bus = displayio.FourWire(d_spi, command=d_dc, chip_select=d_cd,
                                 reset=d_rst, baudrate=1000000)

display = adafruit_ssd1322.SSD1322(d_bus, width=256, height=66, colstart=28)

# Create matrix for controlling pixels of screen
bitmap = displayio.Bitmap(display.width, display.height, 2)
palette = displayio.Palette(2)
palette[0] = 0x000000
palette[1] = 0xffffff
tile_grid = displayio.TileGrid(bitmap, pixel_shader=palette)
group = displayio.Group()
group.append(tile_grid)
display.show(group)

# Draw single pixel on screen at coord (x,y) w/ color (0 or 1)
def drawPixel(x,y):
    bitmap[int(x), int(y)] = 1

obj = gfx.GFX(display.width,display.height,drawPixel)
obj.fill_rect(123,27,10,10)

**Comment by AdinAck** [comment]
Also, keep in mind, I asked the developer of "adafruit_ssd1322.py" if there is a more efficient way to draw a pixel than creating a group with a bitmap and recreating the group every time I want to update the screen (super slow) so if they respond with a solution to that I can update this to not use a bitmap.

**Comment by dherrada** [comment]
Ok. What I think I'm going to do is make that file gfx_ssd1322_simpletest and make the other one gfx_ili3940_simpletest

**Comment by AdinAck** [comment]
Awesome sounds good!
One thing though, I have been continuing to test and improve displaying on the SSD1322, the "drawPixel" function in the script I sent you does not work, I believe just putting "global bitmap" before it would work, but I ended up making an entire class for the display with "self.bitmap" being passed around to a bunch of different functions. I don't know much about pull requests but if you can add that in there that would be good.
Thanks!

**Comment by dherrada** [comment]
If you [look up ssd1322](https://github.com/adafruit?utf8=%E2%9C%93&q=ssd1322&type=&language=) in Adafruit's profile, you'll find the driver repo for that screen. This should apply to almost every other screen Adafruit sells. I think that there should probably be something in the README explaining this to avoid further confusion.
